import { mkdtempSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

// @ts-expect-error This executable module intentionally has no declaration file.
const types = await import("../../scripts/generate-database-types.mjs");
// @ts-expect-error This executable module intentionally has no declaration file.
const verifier = await import("../../scripts/verify-database-types.mjs");

const targetPath = resolve(process.cwd(), "agent/lib/supabase/database.types.ts");

describe("generated Supabase database types", () => {
  it("builds a local-only generator command", () => {
    expect(types.buildGenerateCommand()).toEqual([
      "supabase",
      "gen",
      "types",
      "typescript",
      "--local",
      "--schema",
      "public",
    ]);
    expect(JSON.stringify(types.buildGenerateCommand())).not.toMatch(/--linked|--db-url|--project-id|--project-ref/i);
  });

  it("normalizes only the generator banner and line endings", () => {
    const source = "\ufeff// This file was generated by Supabase.\r\nexport type Json = string\r\n\r\n";
    expect(types.normalizeGeneratedTypes(source)).toBe("export type Json = string\n\n");
  });

  it("rejects empty or non-generated output before any write", () => {
    expect(() => types.validateGeneratedTypes("")).toThrow(/empty|Database/i);
    expect(() => types.validateGeneratedTypes("export type Json = string;")).toThrow(/Database/i);
    expect(() => types.validateGeneratedTypes("export type Json =\nexport type Database = {")).not.toThrow();
  });

  it("writes atomically and preserves the old file when validation fails", () => {
    const directory = mkdtempSync(join(tmpdir(), "database-types-test-"));
    const target = join(directory, "database.types.ts");
    types.writeGeneratedTypesAtomic("export type Json = string;\nexport type Database = {};\n", target);
    expect(readFileSync(target, "utf8")).toContain("export type Database");
    expect(() => types.writeGeneratedTypesAtomic("", target)).toThrow(/empty|Database/i);
    expect(readFileSync(target, "utf8")).toContain("export type Database");
  });

  it("reports byte drift without printing the generated schema", () => {
    expect(verifier.compareGeneratedTypes("same\n", "same\n")).toEqual({ ok: true });
    expect(verifier.compareGeneratedTypes("expected\n", "actual\n")).toMatchObject({
      ok: false,
      category: "TYPE_DRIFT",
    });
    expect(JSON.stringify(verifier.compareGeneratedTypes("postgres://secret", "postgres://actual"))).not.toContain("postgres://");
  });

  it("keeps the committed artifact in the declared location", () => {
    expect(existsSync(targetPath)).toBe(true);
    const source = readFileSync(targetPath, "utf8");
    expect(source).toContain("export type Json =");
    expect(source).toContain("export type Database =");
  });

  it("contains all public tables and critical scope/RPC members", () => {
    const source = readFileSync(targetPath, "utf8");
    for (const table of ["agent_sessions", "care_spaces", "children", "child_access", "clinical_memory_items", "clinical_memory_embeddings", "messages"]) {
      expect(source).toContain(`${table}: {`);
    }
    expect(source).toContain("match_clinical_memory:");
    expect(source).toContain("care_space_id");
    expect(source).toContain("child_id");
    expect(source).toContain("owner_user_id");
  });

  it("verifies the current generated artifact with the local command", () => {
    expect(verifier.buildVerifyCommand()).toEqual(types.buildGenerateCommand());
  });
});
